### PR TITLE
Fix `error.killed` and rename to `error.isTerminated`

### LINKED ISSUE #52: Make `.killed === true` regardless of how it was killed
See: https://github.com/sindresorhus/execa/pull/48/files#r71061011

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #52.

Edit: one test is failing on Windows. Looking into it.

### CODE REVIEW

File: test/error.js [hunk 1]
```diff
@@ -91,59 +87,55 @@ test('failed is true on failure', async t => {
...
 	const subprocess = execa('forever.js');
 
 	process.kill(subprocess.pid, 'SIGINT');
 
 	// `process.kill()` is emulated by Node.js on Windows
 	const message = process.platform === 'win32' ? /failed with exit code 1/ : /was killed with SIGINT/;
-	const {killed} = await t.throwsAsync(subprocess, {message});
-	t.false(killed);
+	const {isTerminated} = await t.throwsAsync(subprocess, {message});
+	t.true(isTerminated);
```
Comment (ehmicky) [inline test/error.js:107]: Change of behavior: now `true` regardless of whether the process was terminated directly or not.

File: test/error.js [hunk 2]
```diff
@@ -91,59 +87,55 @@ test('failed is true on failure', async t => {
...
 
-if (process.platform === 'darwin') {
-	test('sanity check: child_process.exec also has killed.false if killed indirectly', async t => {
-		const promise = pExec('forever.js');
-
-		process.kill(promise.child.pid, 'SIGINT');
-
-		const error = await t.throwsAsync(promise);
-		t.truthy(error);
-		t.false(error.killed);
```
Comment (ehmicky) [inline test/error.js:144]: This does not test Execa, and is not very useful.

File: test/kill.js [hunk 3]
```diff
@@ -82,16 +82,16 @@ test('execa() returns a promise with kill()', t => {
 });
 
 test('timeout kills the process if it times out', async t => {
-	const {killed, timedOut} = await t.throwsAsync(execa('noop.js', {timeout: 1}), {message: TIMEOUT_REGEXP});
-	t.false(killed);
+	const {isTerminated, timedOut} = await t.throwsAsync(execa('noop.js', {timeout: 1}), {message: TIMEOUT_REGEXP});
+	t.true(isTerminated);
```
Comment (ehmicky) [inline test/kill.js:86]: Change of behavior. Timeouts send a signal, so `isTerminated` is `true`.
