### PR TITLE
Fix errors thrown by `.pipe()`

### LINKED ISSUE #853: Fix errors thrown by `.pipe()`
When a series of `.pipe()` is used:

```js
await execa('example')
  .pipe(execa('example'))
  .pipe(execa('example'), {from: 'all'})
```

The error message is not always correct. In the example above, the error should indicate that `from: all` requires the previous process to have the `all: true` option set.

To be able to do this, the last `.pipe()` needs to know what the second `execa()` options are. Since those options are not available on the `childProcess` instance passed to `.pipe()`, it cannot know it. This could be solved by using a global `WeakMap` storing child process options.

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #853.

### CODE REVIEW

File: lib/pipe/throw.js [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+		return sourceError;
+	}
+};
+
+// `.pipe()` awaits the child process promises.
+// When invalid arguments are passed to `.pipe()`, we throw an error, which prevents awaiting them.
+// We need to ensure this does not create unhandled rejections.
+const preventUnhandledRejection = (sourcePromise, destination) => {
+	Promise.allSettled([sourcePromise, destination]);
+};
```
Comment (ehmicky) [inline lib/pipe/throw.js:44]: This file was split from `lib/pipe/validate.js` below. 
The addition to the `preventUnhandledRejection()` function is the only change.

File: test/pipe/template.js [hunk 2]
```diff
@@ -0,0 +1,106 @@
+import {spawn} from 'node:child_process';
```
Comment (ehmicky) [inline test/pipe/template.js:1]: This whole file was split from `test/script.js` but left unchanged.
