### PR TITLE
Fix error handling of `stdin`

### LINKED ISSUE #786: Aborting `childProcess.stdin` leaves the child process hanging
Aborting `childProcess.stdin` does not make the child process end, which can leave it hanging.

```js
const childProcess = execa('forever.js');
childProcess.stdin.destroy();
await childProcess; // Never resolves
```

This applies also to `childProcess.stdio[3]` when using more than one file descriptor, and that file descriptor is used for reading (not writing).

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #786.

### CODE REVIEW

File: lib/stdio/pipeline.js [hunk 1]
```diff
@@ -45,15 +44,6 @@ const handleDestinationComplete = async (source, destination, {signal}) => {
...
 	} catch {} finally {
-		await destroyStream(source);
+		source.destroy();
 	}
 };
-
-// Propagating errors across different streams in the same pipeline can create race conditions.
-// For example, a `Duplex` stream might propagate an error on its writable side and another on its readable side.
-// This leads to different errors being thrown at the top-level based on the result of that race condition.
-// We solve this by waiting for one macrotask with `setImmediate()`.
```
Comment (ehmicky) [inline lib/stdio/pipeline.js:55]: That race condition was actually due to the problem solved by this PR.

File: lib/stream.js [hunk 2]
```diff
@@ -83,20 +95,30 @@ const resumeStream = async stream => {
...
+// But ignores the `childProcess.stdin.destroy()` automatically done on child process exit by Node.js.
+// `controller.signal` is used to ensure this never resolves, only rejects.
+const throwOnInputStdioError = ({spawned, stdioStreamsGroups, processExitPromise, controller}) => spawned.stdio
+	.filter((stream, index) => stream !== null && stdioStreamsGroups[index][0].direction === 'input')
+	.map(stream => throwOnInputStreamError(stream, processExitPromise, controller));
+
+const throwOnInputStreamError = async (stream, processExitPromise, {signal}) => {
+	await Promise.all([
+		Promise.race([
+			processExitPromise,
```
Comment (ehmicky) [inline lib/stream.js:108]: This is due to:

https://github.com/nodejs/node/blob/eca4b1a403959d5b83fb5a9adaae8f4c3580eea2/lib/internal/child_process.js#L278

Calling `childProcess.stdin.destroy()` while a child process is running should be handled as abnormal, since that's aborting its input.
However, Node.js calls `childProcess.stdin.destroy()` when the child process ends, and that is normal. 
Therefore, we use `Promise.race()` so that `finished()` does nothing once the child process has ended.

File: lib/stream.js [hunk 3]
```diff
@@ -83,20 +95,30 @@ const resumeStream = async stream => {
...
+			finished(stream, {cleanup: true, readable: false, writable: true}),
+		]),
+		once(signal, 'abort'),
```
Comment (ehmicky) [inline lib/stream.js:111]: This line is just meant to ensure the function never resolves, since its only purpose is to potentially throw.

File: lib/stream.js (hunk 2 above)
Comment (sindresorhus) [reply lib/stream.js:108]: Maybe add this as a short code comment.

File: lib/stream.js (hunk 3 above)
Comment (sindresorhus) [reply lib/stream.js:111]: Maybe add this as a short code comment.

File: lib/stream.js (hunk 2 above)
Comment (ehmicky) [reply lib/stream.js]: Fixed :+1:

File: lib/stream.js (hunk 3 above)
Comment (ehmicky) [reply lib/stream.js]: Fixed :+1:

File: index.js [hunk 4]
```diff
@@ -155,27 +155,28 @@ export function execa(rawFile, rawArgs, rawOptions) {
 	const controller = new AbortController();
 	setMaxListeners(Number.POSITIVE_INFINITY, controller.signal);
 
+	const originalStreams = [...spawned.stdio];
```
Comment (ehmicky) [inline index.js:158]: Transforms directly modify `spawned.stdin|stdout|stderr`. We need to keep it track of the original values.

File: lib/stdio/async.js [hunk 5]
```diff
@@ -88,10 +88,9 @@ const setStandardStreamMaxListeners = (stream, {signal}) => {
 };
 
 // `source.pipe(destination)` adds at most 1 listener for each event.
-// We also listen for the stream's completion using `finished()`, which adds 1 more listener.
 // If `stdin` option is an array, the values might be combined with `merge-streams`.
 // That library also listens for `source` end, which adds 1 more listener.
-const maxListenersIncrement = 3;
```
Comment (ehmicky) [inline lib/stdio/async.js:94]: Value changed since we are not calling `finished(stream)` on `process.std*` anymore.

File: lib/stream.js [hunk 6]
```diff
@@ -83,19 +102,18 @@ const resumeStream = async stream => {
...
+const waitForCustomStreamsEnd = (stdioStreamsGroups, waitForStream) => stdioStreamsGroups.flat()
 	.filter(({type, value}) => type !== 'native' && !isStandardStream(value))
-	.map(({value}) => finished(value, {cleanup: true}));
-
-const throwIfStreamError = stream => stream === null ? [] : [throwOnStreamError(stream)];
-
-const throwOnStreamError = async stream => {
-	const [error] = await once(stream, 'error');
-	throw error;
-};
```
Comment (ehmicky) [inline lib/stream.js:98]: Previously we only listened to the `error` event for `childProcess.stdin`. 
Now we wait for its completion, which automatically happens when the child process exits.

**Comment by ehmicky** [comment]
Fixed. :+1: 
I reworked the PR too a little.
