### PR TITLE
Ensure process exits on stream errors

### LINKED ISSUE #606: Errors on `stdout`/`stderr` leave the process hanging
When the `stdout`/`stderr` streams of the child process error, the child process is not terminated by Execa.
In most cases, those errors indicate an issue which should also make the child process crash, but that's not always the case.
We should properly exit the process when either on those streams error.

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #606.

### CODE REVIEW

File: lib/stream.js [hunk 1]
```diff
@@ -87,19 +87,20 @@ const applyEncoding = async (stream, maxBuffer, encoding) => {
...
-	const allPromise = getStreamPromise(all, {encoding, buffer, maxBuffer: maxBuffer * 2});
+export const getSpawnedResult = async (spawned, {encoding, buffer, maxBuffer}, processDone) => {
+	const stdoutPromise = getStreamPromise(spawned.stdout, {encoding, buffer, maxBuffer});
+	const stderrPromise = getStreamPromise(spawned.stderr, {encoding, buffer, maxBuffer});
+	const allPromise = getStreamPromise(spawned.all, {encoding, buffer, maxBuffer: maxBuffer * 2});
 
 	try {
 		return await Promise.all([processDone, stdoutPromise, stderrPromise, allPromise]);
 	} catch (error) {
+		spawned.kill();
```
Comment (ehmicky) [inline lib/stream.js:98]: `.kill()` never throws. If the process already exited, it is a noop.

File: test/stream.js [hunk 2]
```diff
@@ -298,3 +298,9 @@ if (process.platform !== 'win32') {
 		t.true(timedOut);
 	});
 }
+
+test('Errors on streams should make the process exit', async t => {
+	const childProcess = execa('forever');
+	childProcess.stdout.destroy();
+	await t.throwsAsync(childProcess, {code: 'ERR_STREAM_PREMATURE_CLOSE'});
+});
```
Comment (ehmicky) [inline test/stream.js:306]: This test fails without the code change above.
