### PR TITLE
Fix `extendEnv` option not working with `shell` option

### LINKED ISSUE #183: `extendEnv` does not work when combined with `shell: true`
The `extendEnv` option does not work as intended when combined with the `shell: true` option:

```js
process.env.TEST = 'test'
const result = execa.sync('echo $TEST', { shell: true, env: {}, extendEnv: true })
assert.equal(result.stdout, 'test')
```

`stdout` is an empty string but should be `'test'`

I will work on a PR to fix this.

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #183 

Options parsing was not correct for the `extendEnv` option which made it not work when combined with `shell: true` option.

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -487,6 +487,14 @@ test('do not extend environment with `extendEnv` option', async t => {
 	]);
 });
 
+test('use extend environment with `extendEnv: true` option', async t => {
```
Comment (sindresorhus) [inline test.js]: The title should mention the purpose is to test it with the `shell` option.

File: test.js [hunk 2]
```diff
@@ -487,6 +487,14 @@ test('do not extend environment with `extendEnv` option', async t => {
...
+	process.env.TEST = 'test';
+	const command = process.platform === 'win32' ? 'echo %TEST%' : 'echo $TEST';
+	const result = await m.shellSync(command, {env: {}, extendEnv: true});
```
Comment (sindresorhus) [inline test.js]: You're awaiting a synchronous method. Should be:

```suggestion
	const result = await m.shell(command, {env: {}, extendEnv: true});
```

The synchronous methods are slow, so we should prefer to use async methods in tests whenever possible.

**Comment by ehmicky** [comment]
Fixed.
