### PR TITLE
Fixes argument parsing for escaped newlines

### LINKED ISSUE #1175: Escaped newlines break arguments in version 9
After upgrading from version 8 to 9, some of my multi-line formatted commands have broken.

Reproduction:

```js
import {$} from "execa";

try {
  // 404 is just a stupid way to get an error for some details.
  // Some commands are large, so I break them up by escaping newlines in templates:
  //   https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#multi-line_strings
  await $`404 abc\
  def`;
} catch (error) {
  console.log("command", error.command); // 404 abc  ef
  console.log("escaped", error.escapedCommand); // 404 "abc " ef
}
```

Expected command: `404 abc  def` or something close enough
Actual commands: `404 abc  ef` or `404 "abc " ef`

I suspect it may be related to the difference between the template strings and the raw strings passed to a tag function. Example:

```js
function poo(foo, ...bar) {
  console.log("strings", foo.slice());
  console.log("raw", foo.raw);
}

poo`404 abc def`;
poo`404 abc
  def`;
poo`404 abc\
  def`;
```

In the first two examples, the raw strings and the strings arrays match up.
```text
strings (1) ['404 abc def']
raw (1) ['404 abc def']

strings (1) ['404 abc
  def']
raw (1) ['404 abc
  def']
```

In the 3rd sample however the generated strings and the raw strings are different.
```text
strings (1) ['404 abc  def']
raw (1) ['404 abc\\
  def']
```

I suspect there may be some code that may be mixing up the raw strings with the regular strings causing some of the escaping to be offset by a character. But that is just a theory 🤷.

### PR DESCRIPTION
**Pull request by aarondandy**
Fixes #1175.

Trying to handle escaped line breaks in template strings.

### CODE REVIEW

**Comment by aarondandy** [comment]
I'm not sure if I have this fix right, even though the test passes.

**Comment by ehmicky** [comment]
Hi @aarondandy,

Thanks, but this should not be needed due to https://github.com/sindresorhus/execa/issues/1175#issuecomment-2523955681

File: test/methods/template.js [hunk 1]
```diff
@@ -22,6 +22,8 @@ test('$ can use newlines and tab indentations', testScriptStdout, () => $`echo.j
 	bar`, 'foo\nbar');
 test('$ can use newlines and space indentations', testScriptStdout, () => $`echo.js foo
   bar`, 'foo\nbar');
+test('$ can use escaped newlines and space indentations', testScriptStdout, () => $`echo.js foo\
+  bar`, 'foo\nbar');
```
Comment (aarondandy) [inline test/methods/template.js:26]: Should the expected actually be `foo bar`?

**Comment by aarondandy** [comment]
Even though this is closed, I still think this indicates a bug in `splitByWhitespaces`. I think my current solution is insufficient though because it does not correctly treat these escaped newlines as token terminators which appears to be the intent of this method. An example that I think may highlight this would be a failure if the next line is unindented. I'm thinking that maybe the behavior that would better fit the intent of this method would be to delimit tokens on these escaped newlines while also correctly adjusting the index values.

File: test/methods/template.js (hunk 1 above)
Comment (aarondandy) [reply test/methods/template.js:26]: Apparently not 🤷.

File: lib/methods/template.js [hunk 2]
```diff
@@ -75,7 +75,12 @@ const splitByWhitespaces = (template, rawTemplate) => {
 			templateStart = templateIndex + 1;
 		} else if (rawCharacter === '\\') {
 			const nextRawCharacter = rawTemplate[rawIndex + 1];
-			if (nextRawCharacter === 'u' && rawTemplate[rawIndex + 2] === '{') {
+			if (nextRawCharacter === '\n') {
```
Comment (aarondandy) [inline lib/methods/template.js:78]: This may need to also handle `\r\n` but I'm not sure how to write a test for that.

File: lib/methods/template.js [hunk 3]
```diff
@@ -75,7 +75,12 @@ const splitByWhitespaces = (template, rawTemplate) => {
...
+				// Handles escaped newlines in templates
+				templateIndex -= 1;
+				rawIndex += 1;
+				continue;
```
Comment (aarondandy) [inline lib/methods/template.js:82]: This `continue` is probably going to make somebody crabby, but my intention here is to explicitly indicate that I'm doing weird stuff to the control flow of the loop because I'm mutating `templateIndex` and putting it temporarily into an invalid state, anticipating that the for loop will re-increment it again resulting in the value remaining stable while the newlines are skipped.

**Comment by ehmicky** [comment]
Let's continue this discussion on #1175.

File: lib/methods/template.js (hunk 2 above)
Comment (ehmicky) [reply lib/methods/template.js:78]: No because escaped newlines inside template strings always use Unix newlines (inside `template.raw`), even on Windows.

File: lib/methods/template.js (hunk 3 above)
Comment (ehmicky) [reply lib/methods/template.js:82]: Yes, I think the code is clear enough without it, and the `continue` here is a noop. 

We have very thorough testing for that file, so if we were to add more logic after those lines in the future, we'd catch any potential problem.

Based on this, I think this `continue` should be removed.

File: test/methods/template.js (hunk 1 above)
Comment (ehmicky) [inline test/methods/template.js:26]: The test looks good. :+1: 

Could you please add the following tests as well?

```js
$`echo.js foo\
  bar` // two spaces, expects: 'foo\nbar'
```

```js
$`echo.js foo\
	bar` // inline tab (not spaces), expects: 'foo\nbar'
```

```js
$`echo.js foo\
\tbar` // escaped tab, expects: 'foo\tbar'
```

```js
$`echo.js foo\
\n\nbar` // escaped newlines, expects: 'foo\n\nbar'
```

Comment (aarondandy) [reply test/methods/template.js:26]: Okay. I also added one for the `foobar` case.

File: test/methods/template.js [hunk 4]
```diff
@@ -22,6 +22,16 @@ test('$ can use newlines and tab indentations', testScriptStdout, () => $`echo.j
...
+test('$ can use escaped newlines and inline tab indentations', testScriptStdout, () => $`echo.js foo\
+	bar`, 'foo\nbar');
+test('$ can use escaped newlines and character escaped tab indentations', testScriptStdout, () => $`echo.js foo\
+\tbar`, 'foo\tbar');
+test('$ can use escaped newlines and character escaped newlines', testScriptStdout, () => $`echo.js foo\
+\n\nbar`, 'foo\n\nbar');
+test('$ can use escaped newlines without indentation', testScriptStdout, () => $`echo.js foo\
+bar`, 'foobar');
```
Comment (ehmicky) [inline test/methods/template.js:34]: This test case already exists below with test name `$ handles escaped newlines`.

File: test/methods/template.js (hunk 1 above)
Comment (ehmicky) [reply test/methods/template.js:26]: Thanks!

File: test/methods/template.js (hunk 4 above)
Comment (aarondandy) [reply test/methods/template.js]: Okay, I removed mine.

**Review by ehmicky — APPROVED** [review]

**Comment by ehmicky** [comment]
Looks good to me. Thanks again @aarondandy.

@sindresorhus Is this good to merge?

**Review by sindresorhus — APPROVED** [review]
